// vue-client/src/views/Home.vue
<template>
  <div class="home">
    <h1>Members</h1>

    <table class="table table-striped" v-if="members">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="member in members" :key="member.id">
          <td>{{ member.id }}</td>
          <td>{{ member.name }}</td>
          <td>{{ member.email }}</td>
          <td class="btn-group">
            <button class="img-btn btn-link" @click="deleteMember(member.id)">
              <img src="/delete.svg" width="12px" height="12px" />
            </button>
            <button class="img-btn btn-link" @click="editMember(member.id)">
              <img src="/edit.svg" width="12px" height="12px" />
            </button>
          </td>
        </tr>
      </tbody>
    </table>

    <p v-else>
      <em>
        Loading...
      </em>
    </p>
  </div>
</template>

<script>
  export default {
    name: "Home",

    data() {
      return {
        members: null
      };
    },

    methods: {
      async deleteMember(memberId) {
        // TODO
        throw "Implement me";
      },

      async editMember(memberId) {
        // TODO
        throw "Implement me";
      }
    },

    async mounted() {
      const response = await fetch("http://localhost:5000/members");
      const data = await response.json();
      this.members = data;
    }
  };
</script>

// angular-client/src/app/home/home.component.ts
import { Component, Inject } from '@angular/core'
import { HttpClient } from '@angular/common/http'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  public members: Member[]

  constructor(http: HttpClient) {
    http.get<Member[]>('http://localhost:5000/members').subscribe(
      (result) => {
        this.members = result
      },
      (error) => console.error(error),
    )
  }

  deleteMember(id) {
    // TODO
    throw 'Implement me'
  }

  editMember(id) {
    // TODO
    throw 'Implement me'
  }
}

interface Member {
  Id: string
  Name: number
  Email: number
}

<h1 id="tableLabel">Members</h1>

<p *ngIf="!members"><em>Loading...</em></p>

<table class="table table-striped" *ngIf="members">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let member of members">
      <td>{{ member.id }}</td>
      <td>{{ member.name }}</td>
      <td>{{ member.email }}</td>
      <td class="btn-group">
        <button class="img-btn btn-link" (click)="deleteMember(member.id)">
          <img src="../../assets/delete.svg" width='12px' height='12px' />
        </button>
        <button class="img-btn btn-link" (click)="editMember(member.id)">
          <img src="../../assets/edit.svg" width='12px' height='12px' />
        </button>
      </td>
    </tr>
  </tbody>
</table>
