// angular-client/src/app/add-member/add-member.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-add-member',
  templateUrl: './add-member.component.html',
})
export class AddMemberComponent {
  addMember() {
    // TODO
    throw 'Implement me'
  }
}

<h1>Add member</h1>

<!-- TODO -->
<!-- Implement me -->

<button class="btn btn-primary" (click)="addMember">
    Add
</button>

// vue-client/src/views/AddMember.vue
<template>
  <div>
    <h1>Add Member</h1>

    <!-- TODO -->
    <!-- Implement me -->
    <button class="btn btn-primary" @click="addMember">
      Add
    </button>
  </div>
</template>

<script>
  export default {
    name: "AddMember",

    methods: {
      async addMember() {
        // TODO
        throw "Implement me";
      }
    }
  };
</script>
